services:
  - type: web
    name: hostelfix-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npx prisma generate
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
